version: "3.7"

services:
    db:
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      volumes:
        - /sagereal/redmine/mysql:/var/lib/mysql
        - /etc/localtime:/etc/localtime:ro
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: redmine

    redmine:
      image: wangxiaoxi/redmine:ubuntu16-3.3.8
      restart: always
      ports:
        - 10083:3000
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /sagereal/redmine/log:/usr/src/redmine/log
        - /sagereal/redmine/data:/usr/src/redmine/files
        - /sagereal/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
        - /sagereal/redmine/config/database.yml:/usr/src/redmine/config/database.yml:ro
        - /sagereal/redmine/config/settings.yml:/usr/src/redmine/config/settings.yml

    nginx:
      image: wangxiaoxi/nginx
      restart: always
      ports:
        - 8006:8006
      volumes:
        - /sagereal/redmine/nginx.conf:/etc/nginx/nginx.conf:ro
        - /sagereal/redmine/log:/var/log/nginx
        - /etc/localtime:/etc/localtime:ro