version: "3"

services:
    db:
      image: sameersbn/mysql:5.7.22-1
      ports:
        - "3306:3306"
      volumes:
        - /home/wangxiaoxi/redmine/mysql:/var/lib/mysql
      environment:
        - DB_NAME=redmine_production
        - DB_USER=redmine
        - DB_PASS=password
      networks:
        - backend

    redmine1:
      image: sameersbn/redmine:3.3.8
      ports:
        - "10083:80"
      volumes:
        - /home/wangxiaoxi/redmine/mysql:/var/lib/mysql
      depends_on:
        - db
      networks:
        - backend
        - frontend
      environment:
        - DB_ADAPTER=mysql2
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=redmine_production
        - DB_USER=redmine
        - DB_PASS=password

    redmine2:
      image: sameersbn/redmine:3.3.8
      ports:
        - "10084:80"
      volumes:
        - /home/wangxiaoxi/redmine/mysql:/var/lib/mysql
      depends_on:
        - db
      networks:
        - backend
        - frontend
      environment:
        - DB_ADAPTER=mysql2
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=redmine_production
        - DB_USER=redmine
        - DB_PASS=password

    redmine3:
      image: sameersbn/redmine:3.3.8
      ports:
        - "10085:80"
      volumes:
        - /home/wangxiaoxi/redmine/mysql:/var/lib/mysql
      depends_on:
        - db
      networks:
        - backend
        - frontend
      environment:
        - DB_ADAPTER=mysql2
        - DB_HOST=db
        - DB_PORT=3306
        - DB_NAME=redmine_production
        - DB_USER=redmine
        - DB_PASS=password

    nginx:
      image: wangxiaoxi/nginx_sticky:1.0
      ports:
        - "80:80"
      depends_on:
        - redmine1
        - redmine2
        - redmine3
      volumes:
        - /home/wangxiaoxi/redmine/nginx.conf:/etc/nginx/nginx.conf:ro
        - /home/wangxiaoxi/log:/var/log/nginx
      networks:
        - frontend

networks:
  backend:
  frontend:
